apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-self-node-remediation-medik8s-io-v1alpha1-selfnoderemediationtemplate
  failurePolicy: Fail
  name: mselfnoderemediationtemplate.kb.io
  rules:
  - apiGroups:
    - self-node-remediation.medik8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - selfnoderemediationtemplates
  sideEffects: None
